apiVersion: apps/v1
kind: Deployment
metadata:
  name: hakap-redis
  labels:
    app: hakap-redis
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hakap-redis
  template:
    metadata:
      labels:
        app: hakap-redis
        tier: backend
    spec:
      containers:
      - name: hakap-redis
        image: "docker.io/redis:6.0.5"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: hakap-redis
  labels:
    app: hakap-redis
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: hakap-redis
    tier: backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hakap-immutability-good
  labels:
    app: hakap-immutability-good
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hakap-immutability-good
      tier: frontend
  template:
    metadata:
      labels:
        app: hakap-immutability-good
        tier: frontend
    spec:
      containers:
      - name: hakap-immutability-good
        image: hakap-immutability-good
        imagePullPolicy: IfNotPresent
        env:
        - name: GET_HOSTS_FROM
          value: "$(HAKAP_REDIS_SERVICE_HOST)"
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1

metadata:
  name: hakap-immutability-good
  labels:
    app: hakap-immutability-good
    tier: frontend
spec:
  type: NodePort
  selector: 
    app: hakap-immutability-good
    tier: frontend
  ports:
    - nodePort: 30290
      port: 8080
